#6 Add support of credit operations
blocksights/blocksights-open-explorer pull request #12
Opened 2022-10-11 11:09 UTC by ihorml

**Issue**: #6 

**Description**:

<img width="1160" alt="Screenshot 2022-10-11 at 14 06 30" src="https://user-images.githubusercontent.com/7770343/195074503-72d2277e-e719-4c93-891a-cbb86a5ecd58.png">

<img width="1155" alt="Screenshot 2022-10-11 at 14 06 42" src="https://user-images.githubusercontent.com/7770343/195074480-3bbf249c-f1b4-4696-b093-467a03ddb088.png">

> @sschiessl-bcp 
> Do credit offer first, then give me an estimate what you think you ll need for all

Answering this - I suppose it's up to 1-2 hours to integrate all the operations from refUI (I found the code with all translations/formats/colors, so technically it's just copy-paste and possibly may take even less time, but not sure how to properly test it, maybe just hardcode the `operation`)

2022-10-11 19:23 UTC, sschiessl-bcp requested changes
Ok, please add the rest

2022-10-11 19:23 UTC, sschiessl-bcp commented on app/core/app.utilities.js
> +                                    accountLink : {
Since you introduce shortcut functions, maybe also do that for links?

2022-10-12 09:14 UTC, ihorml commented
@sschiessl-bcp pushed

2022-10-12 09:14 UTC, ihorml commented on app/core/app.utilities.js
> +                                    accountLink : {
true, pushed

2022-10-16 10:15 UTC, merged