Feature Network URL
blocksights/blocksights-open-explorer pull request #30
Opened 2022-12-23 12:22 UTC by ihorml

**Description**

When you switch to `testnet` any page change in the app will lead to `?network` parameter in the URL. If you switch back to `mainnet` - the `?network` will be removed.

2022-12-23 12:27 UTC, ihorml commented
<img width="274" alt="Screenshot 2022-12-23 at 14 26 05" src="https://user-images.githubusercontent.com/7770343/209336058-144d06ec-c188-42d2-8707-dbd2365bb05a.png">
just noticed there is a different title and the changes by network dropdown doesn't affect it without page reload. Will fix it

2022-12-23 12:36 UTC, ihorml commented
done & pushed

2022-12-23 12:48 UTC, sschiessl-bcp requested changes

2022-12-23 12:48 UTC, sschiessl-bcp commented on app/core/config.route.js
> +                if(url.indexOf('?network') === -1 && activeBlockchain.key === 'testnet') {
The premise is not actually "if testnet", the premise is "if not default"

2022-12-23 12:49 UTC, ihorml commented on app/core/config.route.js
> +                if(url.indexOf('?network') === -1 && activeBlockchain.key === 'testnet') {
Okay, let me clarify first. Are we talking about the `network` or `blockchain`?

2022-12-28 13:15 UTC, ihorml commented
@sschiessl-bcp pushed!

2022-12-29 20:35 UTC, sschiessl-bcp commented
replaced

2022-12-29 20:35 UTC, closed without merging